// Generated by CoffeeScript 1.7.1
var ChartFactory;

ChartFactory = (function() {
  var cf;
  cf = {
    createLineChart: function(target, model) {
      return nv.addGraph(function() {
        var chart;
        chart = nv.models.lineChart().x(function(d) {
          return d[0];
        }).y(function(d) {
          return d[1];
        }).color(d3.scale.category10().range()).useInteractiveGuideline(true);
        chart.margin({
          right: 50,
          bottom: 100
        });
        chart.xAxis.axisLabel('Periodo').tickFormat(function(d) {
          return model.xAxisLabels[d];
        }).rotateLabels(45);
        chart.yAxis.axisLabel('Occorrenze');
        target.datum(model).transition().duration(500).call(chart);
        nv.utils.events.windowResize.addHandler(chart.update);
        return chart;
      });
    }
  };
  return cf;
})();
